version: "3.9"

volumes:
  pde-spring-pg-workspace:
  pde-spring-pg-dotfiles-lvim:

services:
  ide:
    container_name: pde-spring-pg 
    image: ${BASE_IMAGE_TAG}
    command: 
      - /bin/bash
      - -c 
      - | 
        eval `ssh-agent -s`
        ssh-add ~/.ssh/id_rsa
        git clone ${WORKSPACE_REPO_URL} /workspace
        cd ~/.config/nvim
        git remote set-url origin ${LAZYVIM_DOTFILES_REPO_URL}
        sleep infinity
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh/:/root/.ssh/
      - /var/run/docker.sock:/var/run/docker.sock 
      - pde-spring-pg-workspace:/workspace
      # - pde-spring-pg-dotfiles-lvim:/
    ports:
      - "80:8080"
